sudo: false
os: linux
dist: bionic
language: node_js
node_js:
- '14'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
- cd Back-end
- openssl aes-256-cbc -K $encrypted_7d2e031b96a8_key -iv $encrypted_7d2e031b96a8_iv -in plated-inn-286021-firebase-adminsdk-oxi0q-0e23826d54.json.enc -out plated-inn-286021-firebase-adminsdk-oxi0q-0e23826d54.json -d
install:
- npm install
- npm install supertest --save-dev
- apt install gnupg -y
- wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
- echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
- apt update
- apt install -y mongodb-org
- systemctl daemon-reload
- systemctl start mongod
script:
- npm test
- jest --coverage
