sudo: false
language: node_js
node_js:
- '14'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
- cd Back-end
- openssl aes-256-cbc -K $encrypted_7d2e031b96a8_key -iv $encrypted_7d2e031b96a8_iv -in plated-inn-286021-firebase-adminsdk-oxi0q-0e23826d54.json.enc -out plated-inn-286021-firebase-adminsdk-oxi0q-0e23826d54.json -d
install:
- npm install
- npm install supertest --save-dev
script:
- npm test
